# containers => services
services:
  mysql:
    container_name: mysql-first-job-app-container
    ports:
      - "3310:3306"
    image: mysql:8.0.28
    volumes:
      - job-app-config-deamond:/etc/mysql/conf.d
      - first-job-app:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 130320030348753499mysql
    networks:
      - backend
  spring-app:
    image: docker130303/jobapp-dockerrepo:v1.0.0
    container_name: first-job-app-container
    ports:
      - "8085:8080"
    volumes:
      - ./:/app
    networks:
      - backend
#create network
networks:
  backend:
    name: first-job-app-network
    external: true
#create volumes
volumes:
  job-app-config-deamond:
  first-job-app:
