apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: company-db
spec:
  serviceName: "company-db-service"
  replicas: 1
  selector:
    matchLabels:
      app: company-db
  template:
    metadata:
      labels:
        app: company-db
    spec:
      containers:
      - name: company_db_container
        image: mysql:8.0.28
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_DATABASE
          value: companyms_db
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_PASSWORD
        resources:
          requests: 
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: company-db-storage
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
      volumes:
      - name: company-db-storage
        persistentVolumeClaim:
          claimName: company-db-pvc
  volumeClaimTemplates:
  - metadata:
      name: company-db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi